import { DiscordClient } from "@lib/DiscordClient";

// discordjs event names
export type DiscordEvents =
	| "applicationCommandPermissionsUpdate"
	| "autoModerationActionExecution"
	| "autoModerationRuleCreate"
	| "autoModerationRuleDelete"
	| "autoModerationRuleUpdate"
	| "cacheSweep"
	| "channelCreate"
	| "channelDelete"
	| "channelPinsUpdate"
	| "channelUpdate"
	| "debug"
	| "entitlementCreate"
	| "entitlementDelete"
	| "entitlementUpdate"
	| "emojiCreate"
	| "emojiDelete"
	| "emojiUpdate"
	| "error"
	| "guildAuditLogEntryCreate"
	| "guildAvailable"
	| "guildBanAdd"
	| "guildBanRemove"
	| "guildCreate"
	| "guildDelete"
	| "guildIntegrationsUpdate"
	| "guildMemberAdd"
	| "guildMemberAvailable"
	| "guildMemberRemove"
	| "guildMembersChunk"
	| "guildMemberUpdate"
	| "guildScheduledEventCreate"
	| "guildScheduledEventDelete"
	| "guildScheduledEventUpdate"
	| "guildScheduledEventUserAdd"
	| "guildScheduledEventUserRemove"
	| "guildUnavailable"
	| "guildUpdate"
	| "interactionCreate"
	| "invalidated"
	| "inviteCreate"
	| "inviteDelete"
	| "messageCreate"
	| "messageDelete"
	| "messageDeleteBulk"
	| "messageReactionAdd"
	| "messageReactionRemove"
	| "messageReactionRemoveAll"
	| "messageReactionRemoveEmoji"
	| "messageUpdate"
	| "presenceUpdate"
	| "raw"
	| "ready"
	| "roleCreate"
	| "roleDelete"
	| "roleUpdate"
	| "shardDisconnect"
	| "shardError"
	| "shardReady"
	| "shardReconnecting"
	| "shardResume"
	| "stageInstanceCreate"
	| "stageInstanceDelete"
	| "stageInstanceUpdate"
	| "stickerCreate"
	| "stickerDelete"
	| "stickerUpdate"
	| "threadCreate"
	| "threadDelete"
	| "threadListSync"
	| "threadMembersUpdate"
	| "threadMemberUpdate"
	| "threadUpdate"
	| "typingStart"
	| "userUpdate"
	| "voiceServerUpdate"
	| "voiceStateUpdate"
	| "warn"
	| "webhooksUpdate"
	| "webhookUpdate";

// lavalink-client event names
export type LavalinkEvents =
	| "trackStart"
	| "trackEnd"
	| "trackStuck"
	| "trackError"
	| "queueEnd"
	| "playerCreate"
	| "playerMove"
	| "playerDisconnect"
	| "playerSocketClosed"
	| "playerDestroy"
	| "playerUpdate"
	| "playerMuteChange"
	| "playerDeafChange"
	| "playerSuppressChange"
	| "playerQueueEmptyStart"
	| "playerQueueEmptyEnd"
	| "playerQueueEmptyCancel"
	| "playerVoiceJoin"
	| "playerVoiceLeave"
	| "SegmentsLoaded"
	| "SegmentSkipped"
	| "ChapterStarted"
	| "ChaptersLoaded"
	| "debug"
	| "LyricsLine"
	| "LyricsFound"
	| "LyricsNotFound"
	| "create"
	| "destroy"
	| "connect"
	| "reconnecting"
	| "reconnectinprogress"
	| "disconnect"
	| "error"
	| "raw"
	| "resumed";

// event module structure
export interface EventStructure {
	name: DiscordEvents | LavalinkEvents;
	once?: boolean;
	rest?: boolean;
	ws?: boolean;
	player?: boolean;
	node?: boolean;
	execute: (client: DiscordClient, ...args: any) => Promise<any>;
}
