const {
	getTableBorder,
	getRandomInt,
	getRandomColor,
	getRemainingTime,
	getBadges,
	containsLink,
	containsDiscordInvite,
	isHex,
	isValidColor,
	diffHours,
	durationToMillis,
	timeFormat,
	parsePermissions,
} = require("./functions.js");

module.exports = {
	playerButtons: require("./playerButtons.js"),
	getCooldown: require("./getCooldown.js"),
	getTableBorder,
	getRandomInt,
	getRandomColor,
	getRemainingTime,
	getBadges,
	diffHours,
	timeFormat,
	parsePermissions,
	durationToMillis,
	containsLink,
	containsDiscordInvite,
	isHex,
	isValidColor,
};
